name        = "lace_swig"
description = "Provides packages required by bindings produced by the 'swig4ada' tool."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"
tags     = ["binding", "c", "c++"]

project-files = ["library/swig.gpr"]
